import Head from 'next/head'
import { NavBar } from '@/components/navbar/navbar'
import { Footer } from '@/components/footer/footer'
import styles from '../styles/home.module.css'

export default function Home() {
  return (
    <>

      <Head>
        <title>COFFEE SHOP - TIA ROSA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-coffee.svg" />
      </Head>
      <NavBar/>
      <main className={styles.main}>
        <div> aliquyam. Kasd dolor ipsum et kasd, clita nonumy gubergren amet tempor sadipscing. Ea et voluptua no aliquyam, diam dolor at erat diam, elitr sed elitr sit.</div>
      </main>
      <Footer/>
      
    </>
  )
}
