import Head from 'next/head'
import Image from 'next/image'
import { NavBar } from '@/components/navbar/navbar'
import { Footer } from '@/components/footer/footer'
import styles from '../styles/home.module.css'

export default function Home() {
  return (
    <>

      <Head>
        <title>COFFEE SHOP - TIA ROSA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-coffee-pink.svg" />
      </Head>
      <NavBar/>
      <main className={styles.main}>
        <div>
            <Image
              src="/coffee-place.png"
              alt="coffee shop img"
              width={0}
              height={0}
              layout='fill'
              objectFit='cover'
            />
          </div>
          <div className={styles.ctaContainer}>
            <span className={styles.text1}>Um espaço aconchegante <br /><span className={styles.text2}>com aroma de café</span></span>
          </div>          
        </main>
      <Footer/>
      
    </>
  )
}
